// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0-29vCy_wac_iKOc8-LDimFfrQXVjVe4',
    appId: '1:972759723010:web:d76848f1a0dcbd4d410b1b',
    messagingSenderId: '972759723010',
    projectId: 'charcha-9beb4',
    authDomain: 'charcha-9beb4.firebaseapp.com',
    storageBucket: 'charcha-9beb4.appspot.com',
    measurementId: 'G-7M839KRY6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNANERL47xHoUXdnSBMwQbEkPoHQpT7rc',
    appId: '1:641553859317:android:f1b717eccd1c19d60a7bbc',
    messagingSenderId: '641553859317',
    projectId: 'charcha-1c46a',
    storageBucket: 'charcha-1c46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcea-35fz8Uc5YDhNPgbgceteX3rU02eM',
    appId: '1:641553859317:ios:bbe26fdc48f219870a7bbc',
    messagingSenderId: '641553859317',
    projectId: 'charcha-1c46a',
    storageBucket: 'charcha-1c46a.appspot.com',
    iosBundleId: 'com.charcha.app.charcha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWjTaGHBz9P2KJDMOZhFzZGvAPrXbCWQ',
    appId: '1:972759723010:ios:72e7b0576d35852a410b1b',
    messagingSenderId: '972759723010',
    projectId: 'charcha-9beb4',
    storageBucket: 'charcha-9beb4.appspot.com',
    iosBundleId: 'com.charcha.charcha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0-29vCy_wac_iKOc8-LDimFfrQXVjVe4',
    appId: '1:972759723010:web:bb4d4ced31e304fd410b1b',
    messagingSenderId: '972759723010',
    projectId: 'charcha-9beb4',
    authDomain: 'charcha-9beb4.firebaseapp.com',
    storageBucket: 'charcha-9beb4.appspot.com',
    measurementId: 'G-CSWRMXS51V',
  );
}